file-save-path: /Users/gutianyang/大四/上课/Web/find-yummy-backend/src/main/resources/static/uploadFile/
spring:
#  web:
#    resources:
#      static-locations: classpath:/static/
#  servlet:
#    multipart:
#      enabled: true
  jackson:
    serialization:
      indent-output: true

  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/find_yummy
    username:
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true