spring:
  jackson:
    serialization:
      indent-output: true

  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/find_yummy
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true